-- This file is automatically generated by Demulshooter

P1_ChangeCrosshairKey=0x1E
P2_ChangeCrosshairKey=0x30
CrosshairVisibilityKey=0x0F

function lines_from(file)
	lines = {}
	for line in io.lines(file) do
		lines[#lines + 1] = line
	end
	return lines
end
